### ISSUE TITLE
Play command is not sent to chromecast

### ISSUE THREAD

**Issue by nohum** [nohum/chromecast-mqtt-connector#7]
After several connection retries the application ends up with a chromecast object where it thinks that it is connected, but it isn't. In the end, controlling the chromecast does not work:

```
May 10 19:05:14 rouven chromecast[21369]: INFO:pychromecast.controllers:Receiver:Launching app CC1AD845
May 10 19:05:34 rouven chromecast[21369]: WARNING:pychromecast.socket_client:Heartbeat timeout, resetting connection
May 10 19:06:05 rouven chromecast[21369]: ERROR:pychromecast.socket_client:Failed to connect, retrying in 5.000000s
May 10 19:06:05 rouven chromecast[21369]: Traceback (most recent call last):
May 10 19:06:05 rouven chromecast[21369]: File "/usr/local/lib/python3.4/dist-packages/pychromecast/socket_client.py", line 239, in initialize_connection
May 10 19:06:05 rouven chromecast[21369]: self.socket.connect((self.host, self.port))
May 10 19:06:05 rouven chromecast[21369]: File "/usr/lib/python3.4/ssl.py", line 840, in connect
May 10 19:06:05 rouven chromecast[21369]: self._real_connect(addr, False)
May 10 19:06:05 rouven chromecast[21369]: File "/usr/lib/python3.4/ssl.py", line 827, in _real_connect
May 10 19:06:05 rouven chromecast[21369]: socket.connect(self, addr)
May 10 19:06:05 rouven chromecast[21369]: socket.timeout: timed out
May 10 19:07:16 rouven chromecast[21369]: INFO:discovery:removing chromecast with name "Chromecast-Audio-xxxxxx_googlecast._tcp.local."
May 10 19:07:16 rouven chromecast[21369]: WARNING:event:device 192.168.xx.xx is still connected and not removed
May 10 19:09:11 rouven chromecast[21369]: ERROR:pychromecast.socket_client:Failed to connect. No retries.
May 10 19:40:05 rouven chromecast[21369]: DEBUG:mqtt:received mqtt publish of chromecast/192.168.xx.xx/command/player_state with data "b'["http://stream.url", "audio/mpeg"]'"
May 10 19:40:05 rouven chromecast[21369]: DEBUG:event:found device to handle mqtt message
```

**Comment by decke** [comment]
Could be that this was a bug in pychromecast and has been fixed in the meantime. I'm using chromecast-mqtt-connector regularly for half a year now and haven't seen this issue.

**Comment by nohum** [comment]
This very likely, I also never encountered this anymore. Thanks!
